### PR TITLE
email validator should return true for null, undefined and empty values

### PR DESCRIPTION
**Pull request by ecmel**
Fixes https://github.com/monterail/vuelidate/issues/65 and https://github.com/monterail/vuelidate/issues/66

### CODE REVIEW

**Comment by shentao** [comment]
Thank you! :D

**Comment by ecmel** [comment]
Your welcome :)

**Comment by Frizi** [comment]
Thanks! 😀 Can you fix the CI issue please?

```
/home/ubuntu/vuelidate/src/validators/email.js
  3:16  error  Extra semicolon  semi

✖ 1 problem (1 error, 0 warnings)
```

**Comment by ecmel** [comment]
Sorry not experienced on github pull requests :(

**Comment by ecmel** [comment]
I fixed the test case.

Sorry for the mess.

**Comment by Frizi** [comment]
No problem. Just squash the commits please 😃

**Comment by ecmel** [comment]
Done

**Pull request merged**
